export const GET_USERS = "GET_USERS";
export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const GET_SINGLE_USER = "GET_SINGLE_USER";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const STATE = "STATE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_LOGING_IN = "USER_LOGING_IN";
export const USER_LOGGED_IN_SUCCESS = "USER_LOGGED_IN_SUCCESS";
export const USER_LOGGED_IN_FAILED = "USER_LOGGED_IN_FAILED";
export const CLEAR_PRODUCT= "CLEAR_PRODUCT";
export const INSERT_TO_CART= "INSERT_TO_CART";